# 应用端点配置示例

# 保底地址 - 所有请求的默认路由
default_endpoint: "https://api.example.com"

# 端点定义 - key为端点名称，value为端点定义
# 一个application下的端点名称不能重复
endpoints:
  # 最具体的规则：生产环境 + A公司 + 美国地区
  us-a-prod:
    condition: "environment=prod&vendor=company-a&geo_country=US"
    url: "https://us.a.prod.example.com"

  # 较具体的规则：生产环境 + A公司（多个URL）
  a-prod:
    condition: "environment=prod&vendor=company-a"
    url:
      - "https://a.prod.example.com"
      - "http://a.prod.example.com"

  # 一般规则：生产环境 + 公版
  prod-public:
    condition: "environment=prod&vendor=public"
    url: "https://prod.example.com"

  # 基础规则：仅生产环境
  prod-basic:
    condition: "environment=prod"
    url: "https://prod-basic.example.com"

  # 客户端特定规则：移动端
  mobile:
    condition: "client=app"
    url: "https://mobile.example.com"

  # 地理位置规则：中国用户
  china:
    condition: "geo_country=CN"
    url: "https://cn.example.com"

